In [13]:
#opencv tensorflow
#类比 语法 api 原理
#基础数据类型 运算符 流程 字典 数组
import tensorflow as tf
data1=tf.constant(2,dtype=tf.int32)
data2=tf.Variable(10,name='var')
print(data1)
print(data2)
'''sess=tf.Session()
print(sess.run(data1))
init=tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))
sess.close()
'''
init=tf.global_variables_initializer()
sess=tf.Session()
with sess:
    sess.run(init)
    print(sess.run(data2))


Tensor("Const_10:0", shape=(), dtype=int32)
<tf.Variable 'var_10:0' shape=() dtype=int32_ref>
10


In [14]:
#本质 ft=sensor+计算图
#tensor 数据
#op
#graphs 数据操作
#session

In [19]:
import tensorflow as tf
data1=tf.constant(6)
data2=tf.constant(2)
dataAdd=tf.add(data1,data2)
dataMul=tf.multiply(data1,data2)
dataSub=tf.subtract(data1,data2)
dataDiv=tf.divide(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
print('end!')

8
12
4
3.0
end!


In [34]:
import tensorflow as tf
data1=tf.constant(6)
data2=tf.Variable(2)
dataAdd=tf.add(data1,data2)
dataCopy=tf.assign(data2,dataAdd)
dataMul=tf.multiply(data1,data2)
dataSub=tf.subtract(data1,data2)
dataDiv=tf.divide(data1,data2)
init=tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
    print(sess.run(dataCopy))
    print(dataCopy.eval())
    print(tf.get_default_session().run(dataCopy))
    print(sess.run(dataCopy))
    
print('end!')

8
12
4
3.0
8
14
20
26
end!


In [7]:
#placehold
import tensorflow as tf
data1=tf.placeholder(tf.float32)
data2=tf.placeholder(tf.float32)
dataAdd=tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict={data1:6,data2:2}))
    #1 dataAdd 2 data (feed_dict={1:6,2:2})
print('end!')

8.0
end!


In [19]:
# 类比 数组 M行N列[]  内部
#[[6,6]]
import tensorflow as tf
data1=tf.constant([[6,6]])
data2=tf.constant([[2],
                  [2]])
data3=tf.constant([[3,3]])
data4=tf.constant([[1,2],
                  [3,4],
                  [5,6]])
print(data1.shape)
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[0]))
    print(sess.run(data4[:,0]))
    print(sess.run(data4[0,0]))

(1, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1


In [32]:
import tensorflow as tf
data1=tf.constant([[6,6]])
data2=tf.constant([[2],
                  [2]])
data3=tf.constant([[3,3]])
data4=tf.constant([[1,2],
                  [3,4],
                  [5,6]])
data5=tf.constant([[1],[2],[3],[4]])
matMul=tf.matmul(data1,data2)
matAdd=tf.add(data1,data3)
matMul2=tf.multiply(data1,data5)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))
    print(sess.run(matMul2))
    print(sess.run([matAdd,matMul,matMul2]))

[[24]]
[[9 9]]
[[ 6  6]
 [12 12]
 [18 18]
 [24 24]]
[array([[9, 9]]), array([[24]]), array([[ 6,  6],
       [12, 12],
       [18, 18],
       [24, 24]])]


In [37]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])
mat2 = tf.ones([3,2])
mat3 = tf.fill([2,3],15)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[15 15 15]
 [15 15 15]]


In [45]:
import tensorflow as tf
mat1=tf.constant([[2],[3],[4]])
mat2=tf.zeros_like(mat1)
mat3=tf.linspace(0.0,2.0,11)
mat4=tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[ 0.          0.2         0.40000001  0.60000002  0.80000001  1.
  1.20000005  1.39999998  1.60000002  1.80000007  2.        ]
[[ 1.9998548  -0.50301242  0.4119277 ]
 [-0.6352582  -0.6714952   0.57109714]]
